import OpenAI from "openai";
import { env } from "../../config/env";
import {
  getAllocationsPerCourse,
  getCategoryAllocationSummary,
  getCourseRejectionRates,
  getCourseStatistics,
  getOverview,
  getStudentsWithoutFirstPreference,
} from "../analytics/analytics.service";

/**
 * AI Assistant for allocation reporting.
 *
 * Primary path: OpenAI Chat Completions with function-calling. The model is given a
 * set of read-only analytics "tools" (the same functions the dashboard uses). It
 * decides which to call, we execute them against Postgres, and feed the results back
 * so the model answers in natural language. No raw SQL is ever generated by the model.
 *
 * Fallback path: if OPENAI_API_KEY is not set (or the API call fails), a lightweight
 * rule-based matcher answers the four required questions using the same tools, so the
 * assistant is never fully unavailable during evaluation.
 */

export type AssistantResponse = {
  answer: string;
  toolsUsed: string[];
  mode: "openai" | "fallback";
};

// name -> analytics implementation (all read-only, no arguments)
const TOOL_IMPL: Record<string, () => Promise<unknown>> = {
  get_overview: getOverview,
  get_course_statistics: getCourseStatistics,
  get_allocations_per_course: getAllocationsPerCourse,
  get_students_without_first_preference: getStudentsWithoutFirstPreference,
  get_course_rejection_rates: getCourseRejectionRates,
  get_category_allocation_summary: getCategoryAllocationSummary,
};

const TOOLS: OpenAI.Chat.Completions.ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "get_overview",
      description:
        "Top-line totals: number of students, courses, total seats, allocated, unallocated, available seats, and how many got their first preference.",
      parameters: { type: "object", properties: {}, additionalProperties: false },
    },
  },
  {
    type: "function",
    function: {
      name: "get_course_statistics",
      description:
        "Per-course statistics: total/reserved/open seats, seats allocated (open vs reserved), available seats, applicant demand, and rejection rate.",
      parameters: { type: "object", properties: {}, additionalProperties: false },
    },
  },
  {
    type: "function",
    function: {
      name: "get_allocations_per_course",
      description: "How many students were allocated to each course, with seats and availability.",
      parameters: { type: "object", properties: {}, additionalProperties: false },
    },
  },
  {
    type: "function",
    function: {
      name: "get_students_without_first_preference",
      description:
        "List of students who did NOT receive their first preference — either allocated to a lower preference or not allocated at all.",
      parameters: { type: "object", properties: {}, additionalProperties: false },
    },
  },
  {
    type: "function",
    function: {
      name: "get_course_rejection_rates",
      description:
        "Rejection rate per course (applicants who were not allocated to it / applicants), ranked, including the course with the highest rejection rate.",
      parameters: { type: "object", properties: {}, additionalProperties: false },
    },
  },
  {
    type: "function",
    function: {
      name: "get_category_allocation_summary",
      description:
        "Category-wise (GENERAL/OBC/SC/ST) allocation summary: total, allocated, unallocated, and open vs reserved seat usage.",
      parameters: { type: "object", properties: {}, additionalProperties: false },
    },
  },
];

const SYSTEM_PROMPT = `You are the reporting assistant for a university Student Course Allocation System.
Answer questions about students, courses, seats and the allocation result.
Always call the provided tools to get real data before answering — never invent numbers.
Be concise and precise. Use the actual course names, categories and counts returned by the tools.
When useful, present tabular results as a small markdown table. Percentages to one decimal place.
If the data shows no allocations have been run yet (everything zero/unallocated), say so and suggest running the allocation.`;

function getClient(): OpenAI | null {
  if (!env.OPENAI_API_KEY) return null;
  return new OpenAI({ apiKey: env.OPENAI_API_KEY });
}

export async function askAssistant(question: string): Promise<AssistantResponse> {
  const client = getClient();
  if (!client) {
    return ruleBasedAnswer(question);
  }

  const messages: OpenAI.Chat.Completions.ChatCompletionMessageParam[] = [
    { role: "system", content: SYSTEM_PROMPT },
    { role: "user", content: question },
  ];
  const toolsUsed: string[] = [];

  try {
    for (let step = 0; step < 6; step++) {
      const completion = await client.chat.completions.create({
        model: env.OPENAI_MODEL,
        messages,
        tools: TOOLS,
        tool_choice: "auto",
        temperature: 0,
      });

      const message = completion.choices[0]?.message;
      if (!message) break;
      messages.push(message);

      const toolCalls = message.tool_calls ?? [];
      if (toolCalls.length === 0) {
        return {
          answer: message.content?.trim() || "I couldn't produce an answer.",
          toolsUsed,
          mode: "openai",
        };
      }

      for (const call of toolCalls) {
        if (call.type !== "function") continue;
        const impl = TOOL_IMPL[call.function.name];
        toolsUsed.push(call.function.name);
        const result = impl ? await impl() : { error: `Unknown tool: ${call.function.name}` };
        messages.push({ role: "tool", tool_call_id: call.id, content: JSON.stringify(result) });
      }
    }
    return { answer: "The assistant took too many steps without answering.", toolsUsed, mode: "openai" };
  } catch (err) {
    // Fall back gracefully (e.g. invalid key, rate limit, network) so evaluation never breaks.
    const fallback = await ruleBasedAnswer(question);
    return {
      ...fallback,
      answer:
        `_(OpenAI request failed — answered with the built-in analyzer. ` +
        `${err instanceof Error ? err.message : "unknown error"})_\n\n` +
        fallback.answer,
    };
  }
}

// ---------- Keyless fallback ----------

function has(text: string, ...needles: string[]): boolean {
  return needles.some((n) => text.includes(n));
}

async function ruleBasedAnswer(question: string): Promise<AssistantResponse> {
  const q = question.toLowerCase();

  if (has(q, "first preference", "first choice", "first-choice", "top preference")) {
    const data = await getStudentsWithoutFirstPreference();
    if (data.count === 0) {
      return { answer: "Every allocated student received their first preference.", toolsUsed: ["get_students_without_first_preference"], mode: "fallback" };
    }
    const lines = data.students.map(
      (s) =>
        `- **${s.name}** (${s.category}, ${s.marks}) — ` +
        (s.status === "UNALLOCATED"
          ? `not allocated (1st choice: ${s.firstPreference ?? "n/a"})`
          : `got ${s.allocatedCourse} (preference #${s.allocatedPreferencePriority}, 1st choice: ${s.firstPreference ?? "n/a"})`)
    );
    return {
      answer: `**${data.count} student(s)** did not receive their first preference:\n\n${lines.join("\n")}`,
      toolsUsed: ["get_students_without_first_preference"],
      mode: "fallback",
    };
  }

  if (has(q, "reject", "highest rejection", "most competitive")) {
    const data = await getCourseRejectionRates();
    if (!data.highestRejectionCourse) {
      return { answer: "No applications on record yet, so rejection rates can't be computed.", toolsUsed: ["get_course_rejection_rates"], mode: "fallback" };
    }
    const top = data.highestRejectionCourse;
    const table = ["| Course | Applicants | Allocated | Rejected | Rejection % |", "| --- | ---: | ---: | ---: | ---: |"]
      .concat(data.ranking.map((r) => `| ${r.courseName} | ${r.applicants} | ${r.allocated} | ${r.rejected} | ${r.rejectionRatePercent}% |`))
      .join("\n");
    return {
      answer: `**${top.courseName}** had the highest rejection rate at **${top.rejectionRatePercent}%** (${top.rejected} of ${top.applicants} applicants not placed there).\n\n${table}`,
      toolsUsed: ["get_course_rejection_rates"],
      mode: "fallback",
    };
  }

  // Word-boundary match so a bare category code like "st"/"sc" does not match
  // inside words such as "student"/"course".
  if (/\bcategor|category-wise|\bobc\b|\bsc\b|\bst\b|\bgeneral\b|reservation/.test(q)) {
    const data = await getCategoryAllocationSummary();
    const table = ["| Category | Students | Allocated | Unallocated | Via Open | Via Reserved |", "| --- | ---: | ---: | ---: | ---: | ---: |"]
      .concat(data.map((c) => `| ${c.category} | ${c.totalStudents} | ${c.allocated} | ${c.unallocated} | ${c.viaOpenSeat} | ${c.viaReservedSeat} |`))
      .join("\n");
    return { answer: `Category-wise allocation summary:\n\n${table}`, toolsUsed: ["get_category_allocation_summary"], mode: "fallback" };
  }

  if (has(q, "each course", "per course", "allocated to", "how many", "seats", "available")) {
    const data = await getAllocationsPerCourse();
    const table = ["| Course | Allocated | Total Seats | Available |", "| --- | ---: | ---: | ---: |"]
      .concat(data.map((c) => `| ${c.courseName} | ${c.allocated} | ${c.totalSeats} | ${c.availableSeats} |`))
      .join("\n");
    return { answer: `Allocations per course:\n\n${table}`, toolsUsed: ["get_allocations_per_course"], mode: "fallback" };
  }

  // Default: overview + guidance.
  const overview = await getOverview();
  return {
    answer:
      `Here's the current overview (set \`OPENAI_API_KEY\` for full natural-language Q&A):\n\n` +
      `- Students: **${overview.totalStudents}**, Courses: **${overview.totalCourses}**, Total seats: **${overview.totalSeats}**\n` +
      `- Allocated: **${overview.totalAllocated}**, Unallocated: **${overview.unallocated}**, Available seats: **${overview.availableSeats}**\n` +
      `- Received first preference: **${overview.gotFirstPreference}**\n\n` +
      `Try: "How many students were allocated to each course?", "Which students did not get their first preference?", ` +
      `"Which course had the highest rejection rate?", or "Show the category-wise allocation summary."`,
    toolsUsed: ["get_overview"],
    mode: "fallback",
  };
}
